# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoolQuestion',
            fields=[
                ('id', models.CharField(default=main.models.generateUUID, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('prompt', models.TextField(max_length=500, null=True)),
                ('expiration', models.DateTimeField(verbose_name='expires')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoolResponse',
            fields=[
                ('id', models.CharField(default=main.models.generateUUID, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('session_key_of_creator', models.CharField(max_length=255)),
                ('vote_resp', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BoolQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCOption',
            fields=[
                ('id', models.CharField(default=main.models.generateUUID, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('option', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.CharField(default=main.models.generateUUID, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('prompt', models.TextField(max_length=500, null=True)),
                ('expiration', models.DateTimeField(verbose_name='expires')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCResponse',
            fields=[
                ('id', models.CharField(default=main.models.generateUUID, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('session_key_of_creator', models.CharField(max_length=255)),
                ('vote_resp', models.IntegerField(default=1)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mcoption',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.MCQuestion'),
        ),
    ]
