# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boolquestion',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='expiration',
        ),
    ]
